apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pubsub-sender
  name: pubsub-sender
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pubsub-sender
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pubsub-sender
    spec:
      containers:
      - env:
        - name: PUBSUB_VERIFICATION_TOKEN
          valueFrom:
            configMapKeyRef:
              key: PUBSUB_VERIFICATION_TOKEN
              name: pubsub-sender-config-ym7i
        - name: PUBSUB_TOPIC
          valueFrom:
            configMapKeyRef:
              key: PUBSUB_TOPIC
              name: pubsub-sender-config-ym7i
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_CLOUD_PROJECT
              name: pubsub-sender-config-ym7i
        - name: STATUS_TABLE_ID
          valueFrom:
            configMapKeyRef:
              key: STATUS_TABLE_ID
              name: pubsub-sender-config-ym7i
        - name: DELAY
          valueFrom:
            configMapKeyRef:
              key: DELAY
              name: pubsub-sender-config-ym7i
        image: gcr.io/for-adrian/pubsub-sender@sha256:e5c848d2d01d52628257a8d12f087525fd72a3dff3a0686399d22ab36ab2fd6e
        imagePullPolicy: IfNotPresent
        name: pubsub-sender-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
