apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pubsub-worker
  name: pubsub-worker
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pubsub-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pubsub-worker
    spec:
      containers:
      - env:
        - name: PUBSUB_VERIFICATION_TOKEN
          valueFrom:
            configMapKeyRef:
              key: PUBSUB_VERIFICATION_TOKEN
              name: pubsub-worker-config
        - name: PUBSUB_TOPIC
          valueFrom:
            configMapKeyRef:
              key: PUBSUB_TOPIC
              name: pubsub-worker-config
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_CLOUD_PROJECT
              name: pubsub-worker-config
        - name: STATUS_TABLE_ID
          valueFrom:
            configMapKeyRef:
              key: STATUS_TABLE_ID
              name: pubsub-worker-config
        - name: DATA_TABLE_ID
          valueFrom:
            configMapKeyRef:
              key: DATA_TABLE_ID
              name: pubsub-worker-config
        - name: MINER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # Change here to include your Container URL to pull
        image: gcr.io/PROJECT_ID/pubsub_worker:latest
        imagePullPolicy: IfNotPresent
        name: pubsub-worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
